// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProductConfigurationMicroservice_Data;

#nullable disable

namespace ProductConfigurationMicroservice_Data.Migrations
{
    [DbContext(typeof(ProductConfigurationDbContext))]
    partial class ProductConfigurationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProductConfigurationMicroservice_Data.Entities.ProductConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductItemId")
                        .HasColumnType("integer")
                        .HasColumnName("product_item_id");

                    b.Property<int>("VariationOptionId")
                        .HasColumnType("integer")
                        .HasColumnName("variation_option_id");

                    b.HasKey("Id");

                    b.HasIndex("ProductItemId", "VariationOptionId")
                        .IsUnique();

                    b.ToTable("product_configuration", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
